services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springuserpassword
      MYSQL_DATABASE: job_db
    ports:
      - "3306:3306"

